### ISSUE TITLE
perform co-adding step _after_ all corrections/calibrations on each image

### ISSUE THREAD

**Issue by falkben** [spacetelescope/DRESSCode#52]
# Todo

- [x] Move step 11 (corrections) before step 10 (uvotimsum)
  - [x] update the mask with pixels that are `NaN` in the exposure map and pixels that have very low exposure times https://github.com/spacetelescope/DRESSCode/blob/860ebd01b0ba760acd5e3acfe66a72164591a4b2/dresscode/uvotimsum.py#L172-L178
  - [x] apply mask to data BEFORE corrections (I think we can just multiple data by mask)
  - [x] apply normalization _before_ applying corrections, as those need to be in counts/sec
    - [x] normalization needs to be done frame by frame, so we cannot use `farith`, since it seems to only work on the primary array
  - [x] run the corrections for every frame in a file instead of on the summed data
    - [x] save the "planes" as separate files from coinc. loss corr (3 files, primary, coincidence loss correction factor, and relative coincidence loss correction uncertainty (fraction))
    - [x] only apply large scale sensitivity correction and zero point correction to corrected data from the coincidence loss corr. (not the other planes/files)
  - [x] separate file for the zero_point correction factor (ZPCORR)
  - [x] undo the normalization -> counts / sec -> counts (mult. by exposure map), for summing
- [x] Remove step 9 (sort_by_year) as we will not be summing within the year
- [x] Step 10 (call into `uvotimsum`) replace step 12, since the summing can now be done in a single step
  - [x] primary data can summed with uvotimsum, after converting to counts (undoing the normalization) https://github.com/spacetelescope/DRESSCode/blob/860ebd01b0ba760acd5e3acfe66a72164591a4b2/dresscode/combine.py#L164
  - [x] exposure maps need to be summed as well with uvotimsum, w/ special keyword for expmaps
  - [x] "coincidence loss correction factor": cannot simply be summed. What we want is a weighted average of the factors (weighted by counts). To achieve this, we can “undo” the correction for a moment and calculate the counts as if no coincidence correction happened, i.e. `orig_counts = primary / corr_factor` (where orig_counts is the uncorrected counts). Make sure primary is in counts. We can then sum all the or_counts with uvotimsum in the same way as we sum primary. The weighted correction factor for the summed image is then `F = summed_primary / summed_orig_counts`. https://github.com/spacetelescope/DRESSCode/blob/860ebd01b0ba760acd5e3acfe66a72164591a4b2/dresscode/combine.py#L279-L284
  - [x] "coincidence loss correction uncertainty": convert the uncertainty from a relative fraction to an uncertainty in counts, by multiplying the rel_unc frame with the primary frame (in counts). https://github.com/spacetelescope/DRESSCode/blob/860ebd01b0ba760acd5e3acfe66a72164591a4b2/dresscode/combine.py#L138-L141 Take the squares of all the frames, and then sum these squares with uvotimsum. After the summing, take the square root. I noticed that I did this wrong in `combine.py` (I summed the uncertainties, not their squares, oops).
  - [x] The ZPCORR is 1 value per frame, but to do a similar weighted average as for the coi loss factor, a new frame can be created that has ZPCORR as value in every pixel. https://github.com/spacetelescope/DRESSCode/blob/860ebd01b0ba760acd5e3acfe66a72164591a4b2/dresscode/combine.py#L170 Can then sum the same way as we do w/ the coi loss factor https://github.com/spacetelescope/DRESSCode/blob/860ebd01b0ba760acd5e3acfe66a72164591a4b2/dresscode/combine.py#L286-L291
- [x] `combine.py` should no longer be needed for it's main purpose (combining the summed data across the years), but need to make sure we have the data in the right format before doing the steps in calibration. Should contain 4 planes: 
  - [x] primary (counts/s)
  - [x] average coincidence loss correction factor
  - [x] relative coincidence loss correction uncertainty (fraction)
  - [x] average zero point correction factor
  - [x] relative Poisson noise (fraction): `1.0 / np.sqrt(primary)`
- [x] Remove years from `config.txt`
- [x] Remove `enlarge` `add_xpix` and `add_ypix` from `config.txt`
- [x] Update docs with the new order of steps

## Current steps

|step|script|input|output|
|-|-|-|-|
|08|uvotskylss|`*sk_corr.img` |`output_uvotskylss_{...}_uat_{evt,img}_{FFF}_sk_corr.txt`,`{...}_uat_{evt,img}_{FFF}_lss_corr.img`|
|09|sort_by_year| | files moved into folders |
|10|uvotimsum| |`all_{FFF}_{ex,lss,mk,sk}.img`,`output_uvotimsum_{FFF}_{ex,lss,sk}.txt`,`sum_{FFF}_{ex,lss,nm,sk}.img`,`{...}_uat_{evt,img}_{FFF}_mk_corr_new.img`|
|11|corrections| |`sum_{FFF}_nm_{coi,coilss,coilsszp}.img`|
|12|combine| |`total_sum_{FFF}_{ex,nm,sk}.fits`, `sum_{FFF}_ex_r.img`, `sum_{FFF}_nm_coilsszp_{c,c_r}.img`|
|13|calibration| |`NGC0628_final_{FFF}_Jy.fits`|

## When finished

When finished should look something like this, with inputs/outputs still to be defined

|step|script|input|output|
|-|-|-|-|
|08|uvotskylss|`*sk_corr.img` |`output_uvotskylss_{...}_uat_{evt,img}_{FFF}_sk_corr.txt`,`{...}_uat_{evt,img}_{FFF}_lss_corr.img`|
|09|corrections| |???|
|10|uvotimsum| |???|
|11|calibration| |`NGC0628_final_{FFF}_Jy.fits`|

**Comment by falkben** [comment]
Notes: 

- use uvotimsum to combine to a single observation, this would be before applying corrections (so before step 9)
- for vectorized std: might think about using a sliding window for calculating percentiles over a window (https://docs.scipy.org/doc/scipy/reference/reference/ndimage.html#module-scipy.ndimage) — e.g. approximate std as 0.5 * (84th - 16th percentile ). Also https://numpy.org/devdocs/reference/generated/numpy.lib.stride_tricks.sliding_window_view.html
